  pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/D4ig0/Tingeso-pep-1']])
                    dir ("tingeso_pep_1"){
                        sh "mvn clean install"
                    }
                }
            }

        stage("Test"){
            steps{
                dir("tingeso_pep_1"){
                    sh "mvn test"
                }
            }
        }
        stage("SonarQube Analysis"){
            steps{
                dir("tingeso_pep_1"){
                    sh "mvn clean verify sonar:sonar  -Dsonar.projectKey=tingeso_pep_1  -Dsonar.projectName='tingeso_pep_1'  -Dsonar.host.url=http://localhost:9000/  -Dsonar.token=sqp_ca64b9b97e4ea19e8c8d93385501ba8c7ad413a7"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("tingeso_pep_1"){
                    sh "docker build -t d4ig0/tingeso_pep_1 ."
                }

            }
        }
        stage("Push Docker Image"){
            steps{
                dir("tingeso_pep_1"){
                   withCredentials([string(credentialsId: 'dckhubPassword', variable: 'dockerPass')]) {
                        sh "docker login -u d4ig0 -p ${dockerPass}"

                    }
                    sh "docker push d4ig0/tingeso_pep_1"

                }

            }
        }
    }

    post{
        always{
            dir("tingeso_pep_1"){
                sh "docker logout"
            }
        }
    }
}
 